[platformio]
src_dir = .

; PlatformIO 项目配置
; 电动自行车 BSD 转向灯系统
; 板载: ESP32 Dev Module
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bblanchon/ArduinoJson @ ^7
    mathieucarbou/AsyncTCP @ ^3
    mathieucarbou/ESPAsyncWebServer @ ^3
